### ISSUE TITLE
Pausing & resuming map cause scalebar to have an error

### ISSUE THREAD

**Issue by RogerKoh** [Esri/arcgis-runtime-toolkit-android#163]
Hi,

   I was trying out the scale bar & compass using 100.6 toolkit.
   Both are performing well when the map is active.
   However, if user minimize the map app & resume back, the scalebar class will have an error in ondraw method, line 455, stating:

    com.esri.arcgisruntime.ArcGISRuntimeException: Invalid argument: can not assign an empty point to a vertex
    ...
   at com.esri.arcgisruntime.toolkit.scalebar.Scalebar.onDraw(Scalebar.kt:455)

   Can anyone assist to identify what is causing the issue?
   Thank you so much.

**Comment by LDuncAndroid** [comment]
Can you share some of your code? It will help with debugging.
