### ISSUE TITLE
File Size increasing

### ISSUE THREAD

**Issue by NamitGoyal26** [Esri/arcgis-runtime-toolkit-android#195]
After adding the arcgis sdk into my android application and run the application the file size of my application increases 485 MB.
And the size of the apk becomes 72 MB.

**Comment by mbcoder** [comment]
@NamitGoyal26 as your question related to the ArcGIS Runtime SDK you are best posting your question in this [community](https://community.esri.com/t5/arcgis-runtime-sdk-for-android/bd-p/arcgis-runtime-sdk-for-android-questions)

There was a question similar this this recently which has links to the resources you need to make smaller apks

https://community.esri.com/t5/arcgis-runtime-sdk-for-android/apk-size-is-huge-i-looked-and-arcgis-sdk-100-7-has-a-library/td-p/1068250/jump-to/first-unread-message
